import React, {  useEffect, useState } from 'react'
import Head from 'next/head'
import Coin from '../components/Coin'
import SearchCoin from '../components/SearchCoin'
import img from '../public/hand-money-euro-coin.png'
import styled from 'styled-components'


const Wrapper = styled.div`
  width: 100%;
  height: 100vh;
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 40% 10% 50%;
  background-color: #f9f9f9;
  color: #124a63;
`
const Coins = styled.div`
  width: 60%;
  height: 90%;
  display: flex;
  justify-self: center;
  flex-direction: column;
  overflow: scroll;
  -ms-overflow-style: none;
  scrollbar-width: none; 
  &::-webkit-scrollbar {
  display: none;
} 
`
const Navigation = styled.div`
    justify-self: center;
    width: 60%;
    height: 40px;
    display: grid;
    background-color: #f9f9f9;
    color: #b3c5cd;
    grid-template-columns: repeat(5, 1fr);
    margin-bottom: 25px;
    p:first-child{
      font-size: 20px;
      font-weight: bold;
      text-align: center;
      grid-column: 1/2;
    }
    p:nth-child(2){
      font-size: 20px;
      font-weight: bold;
      text-align: right;
      grid-column: 3/4;
    }
    p:nth-child(3){
      font-size: 20px;
      font-weight: bold;
      text-align: right;
      grid-column: 4/5;
    }
    p:nth-child(4){
      font-size: 20px;
      font-weight: bold;
      text-align: right;
      grid-column: 5/6;
      padding-right: 10px;
    }
`



export default function Home({coins}) {
  const [inputValue, setInputValue] = useState('');
  const [isLogged, setIsLogged] = useState('');

  const searchCoin = coins.filter(coin => coin.name.toLowerCase().includes(inputValue.toLowerCase()));

  useEffect(() => {
    const data = localStorage.getItem('isLogged');
    if(data) setIsLogged(data);
  }, [])

  return (
    
    <Wrapper>
      <Head>
        <title>Crypto Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <SearchCoin img={img} isLogged={isLogged} coin={coins} setIsLogged={setIsLogged} setInputValue={setInputValue} />
        <Navigation><p>Coin</p><p>Price</p><p>24H Change</p><p>Market Cap</p></Navigation>
        <Coins>
        
        {searchCoin.map(coin => <Coin key={coin.id} coin={coin} />)}
        </Coins>
    </Wrapper>
  )
}

export const getServerSideProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=30&page=1&sparkline=false')
  const data = await res.json();

  return {
    props: {
      coins: data
    }
  }
}
